/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * TickX Trading Core API
 * OpenAPI spec version: 0.0.12
 */

export type AdminTradingStateDtoSignal = typeof AdminTradingStateDtoSignal[keyof typeof AdminTradingStateDtoSignal];


export const AdminTradingStateDtoSignal = {
  price_interrupted: 'price_interrupted',
  price_resumed: 'price_resumed',
} as const;
