/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * TickX Trading Core API
 * OpenAPI spec version: 0.0.12
 */
import type { AdminTradingStateDtoSignal } from './adminTradingStateDtoSignal';

export interface AdminTradingStateDto {
  readonly marketId: string;
  readonly healthy: boolean;
  readonly autoHealthy: boolean;
  readonly manualPauseActive: boolean;
  readonly signal: AdminTradingStateDtoSignal;
  readonly reason: string;
  readonly source: string;
  readonly ts: number;
}
