/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Tapl Bot API
 * OpenAPI spec version: 0.0.12
 */

export interface CommitBatchDto {
  /** Transaction hash of the commit transaction */
  txHash: string;
  /** Merkle root of the batch */
  merkleRoot: string;
  /** Unix timestamp (seconds) when the batch was committed */
  committedAt: number;
}
