/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Tapl Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { DistributionControllerGetPendingBatches200BatchesItemDestinationsItem } from './distributionControllerGetPendingBatches200BatchesItemDestinationsItem';
import type { DistributionControllerGetPendingBatches200BatchesItemLpSharesItem } from './distributionControllerGetPendingBatches200BatchesItemLpSharesItem';

export type DistributionControllerGetPendingBatches200BatchesItem = {
  epochId?: number;
  totalRewards?: string;
  snapshotBlock?: number;
  lpShares?: DistributionControllerGetPendingBatches200BatchesItemLpSharesItem[];
  destinations?: DistributionControllerGetPendingBatches200BatchesItemDestinationsItem[];
};
