/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * TickX Trading Core API
 * OpenAPI spec version: 0.0.12
 */

export interface LeaderboardEntryDto {
  readonly rank: number;
  readonly userId: string;
  readonly pnl: string;
  readonly settledOrders: number;
  readonly wins: number;
  readonly losses: number;
  readonly totalVolume: string;
  readonly miniAppUsername: string;
  readonly humanVerified: boolean;
}
