/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * TickX Trading Core API
 * OpenAPI spec version: 0.0.12
 */

export type LeaderboardControllerGetLeaderboardWindow = typeof LeaderboardControllerGetLeaderboardWindow[keyof typeof LeaderboardControllerGetLeaderboardWindow];


export const LeaderboardControllerGetLeaderboardWindow = {
  '1d': '1d',
  '7d': '7d',
  '30d': '30d',
  all: 'all',
} as const;
