/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * TickX Trading Core API
 * OpenAPI spec version: 0.0.12
 */

export interface MiniAppWalletAuthSuccessPayloadDto {
  status: string;
  message: string;
  signature: string;
  address: string;
  version: number;
}
