/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * TickX Trading Core API
 * OpenAPI spec version: 0.0.12
 */
import type { MiniAppWalletAuthSuccessPayloadDto } from './miniAppWalletAuthSuccessPayloadDto';

export interface MiniAppLoginDto {
  nonce: string;
  payload: MiniAppWalletAuthSuccessPayloadDto;
  miniAppUserId: string;
  miniAppUsername?: string;
}
