/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * TickX Trading Core API
 * OpenAPI spec version: 0.0.12
 */
import type { MiniAppVerifyHumanPayloadDto } from './miniAppVerifyHumanPayloadDto';

export interface MiniAppVerifyHumanDto {
  action: string;
  signal: string;
  payload: MiniAppVerifyHumanPayloadDto;
}
