/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Tapl Bot API
 * OpenAPI spec version: 0.0.12
 */

export type OhlcControllerGetOhlc200CandlesItem = {
  timestamp?: number;
  open?: string;
  high?: string;
  low?: string;
  close?: string;
};
