/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * TickX Trading Core API
 * OpenAPI spec version: 0.0.12
 */

export type OrderControllerGetUserOrdersStatus = typeof OrderControllerGetUserOrdersStatus[keyof typeof OrderControllerGetUserOrdersStatus];


export const OrderControllerGetUserOrdersStatus = {
  OPEN: 'OPEN',
  NEED_RESETTLEMENT: 'NEED_RESETTLEMENT',
  SETTLED: 'SETTLED',
  REJECTED: 'REJECTED',
} as const;
