/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Tapl Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { OrderControllerGetUserOrdersStatus } from './orderControllerGetUserOrdersStatus';

export type OrderControllerGetUserOrdersParams = {
/**
 * Filter by order status
 */
status?: OrderControllerGetUserOrdersStatus;
/**
 * Number of orders to return (min: 1)
 */
limit?: number;
/**
 * Number of orders to skip (min: 0)
 */
offset?: number;
};
