/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * TickX Trading Core API
 * OpenAPI spec version: 0.0.12
 */
import type { OrderControllerGetUserOrdersStatus } from './orderControllerGetUserOrdersStatus';

export type OrderControllerGetUserOrdersParams = {
/**
 * Filter by order status
 */
status?: OrderControllerGetUserOrdersStatus;
/**
 * Number of orders to return (min: 1)
 */
limit?: number;
/**
 * Number of orders to skip (min: 0)
 */
offset?: number;
/**
 * Only return orders with placedAt >= fromTime (unix ms)
 */
fromTime?: number;
/**
 * Only return orders with placedAt <= toTime (unix ms)
 */
toTime?: number;
};
