/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * TickX Trading Core API
 * OpenAPI spec version: 0.0.12
 */
import type { Cell } from './cell';

export interface PlaceOrderDto {
  cell: Cell;
  marketId: string;
  amount: string;
}
