/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Tapl Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { PublicUserAuthProfileDtoAuthType } from './publicUserAuthProfileDtoAuthType';

export interface PublicUserAuthProfileDto {
  address: string;
  authType: PublicUserAuthProfileDtoAuthType;
  humanVerified: boolean;
  /** @nullable */
  miniAppUserId: string | null;
  /** @nullable */
  miniAppUsername: string | null;
  /** @nullable */
  humanVerifiedAt: string | null;
}
