/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * TickX Trading Core API
 * OpenAPI spec version: 0.0.12
 */

export type PublicUserAuthProfileDtoAuthType = typeof PublicUserAuthProfileDtoAuthType[keyof typeof PublicUserAuthProfileDtoAuthType];


export const PublicUserAuthProfileDtoAuthType = {
  wallet: 'wallet',
  miniapp: 'miniapp',
} as const;
