/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * TickX Trading Core API
 * OpenAPI spec version: 0.0.12
 */
import type { RiskControllerGetLiability200Breakdown } from './riskControllerGetLiability200Breakdown';

export type RiskControllerGetLiability200 = {
  timestamp?: number;
  /** Total balance of all users (free + locked) in wei */
  totalLiability?: string;
  utilizationBps?: number;
  maxSingleBetExposure?: string;
  outstandingBets?: number;
  breakdown?: RiskControllerGetLiability200Breakdown;
};
