/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Tapl Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { SettlementControllerGetPendingBatches200BatchesItem } from './settlementControllerGetPendingBatches200BatchesItem';

export type SettlementControllerGetPendingBatches200 = {
  batches?: SettlementControllerGetPendingBatches200BatchesItem[];
};
