/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Tapl Bot API
 * OpenAPI spec version: 0.0.12
 */

export type SettlementControllerGetPendingBatchesParams = {
/**
 * Unix timestamp (seconds) - window start
 */
windowStart: number;
/**
 * Unix timestamp (seconds) - window end
 */
windowEnd: number;
};
