/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * TickX Trading Core API
 * OpenAPI spec version: 0.0.12
 */
import type { SettlementControllerGetPendingBatches200BatchesItemSettlementsItemOutcome } from './settlementControllerGetPendingBatches200BatchesItemSettlementsItemOutcome';

export type SettlementControllerGetPendingBatches200BatchesItemSettlementsItem = {
  account?: string;
  betId?: string;
  outcome?: SettlementControllerGetPendingBatches200BatchesItemSettlementsItemOutcome;
  payout?: string;
  originalStake?: string;
};
