/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Tapl Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { SettlementControllerGetPendingBatches200BatchesItemDepositsItem } from './settlementControllerGetPendingBatches200BatchesItemDepositsItem';
import type { SettlementControllerGetPendingBatches200BatchesItemSettlementsItem } from './settlementControllerGetPendingBatches200BatchesItemSettlementsItem';
import type { SettlementControllerGetPendingBatches200BatchesItemWithdrawalsItem } from './settlementControllerGetPendingBatches200BatchesItemWithdrawalsItem';

export type SettlementControllerGetPendingBatches200BatchesItem = {
  batchId?: string;
  windowStart?: number;
  windowEnd?: number;
  deposits?: SettlementControllerGetPendingBatches200BatchesItemDepositsItem[];
  withdrawals?: SettlementControllerGetPendingBatches200BatchesItemWithdrawalsItem[];
  settlements?: SettlementControllerGetPendingBatches200BatchesItemSettlementsItem[];
};
